version: "3.8"

services:
  homey-assistant:
    image: ghcr.io/pigmej/homey-assistant-agent:latest
    volumes:
      - ${MCP_CONFIG_PATH:-./mcp.json}:/app/mcp.json:ro
      - ${ENV_FILE_PATH:-./.env}:/app/.env:ro
    environment:
      - MCP_CONFIG_PATH=/app/mcp.json
    restart: unless-stopped
